/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaevaluacionturistica;

/**
 *
 * @author Usuario
 */
public class CapturaComentario extends javax.swing.JFrame {

    /**
     * Creates new form CapturaComentario
     */
    FuncionesEvaluacion fe;
    String name;
    public void cargarComentario(){
        if(fe.state==1){
            if(name.compareTo("1")==0){
                txta_comentario.setText(fe.comentario1_1);
            }
            if(name.compareTo("2")==0){
                txta_comentario.setText(fe.comentario1_2);
            }
            if(name.compareTo("3")==0){
                txta_comentario.setText(fe.comentario1_3);
            }
            if(name.compareTo("4")==0){
                txta_comentario.setText(fe.comentario1_4);
            }
            if(name.compareTo("5")==0){
                txta_comentario.setText(fe.comentario1_5);
            }
        }
        if(fe.state==2){
            if(name.compareTo("1")==0){
                txta_comentario.setText(fe.comentario2_1);
            }
            if(name.compareTo("2")==0){
                txta_comentario.setText(fe.comentario2_2);
            }
            if(name.compareTo("3")==0){
                txta_comentario.setText(fe.comentario2_3);
            }
            if(name.compareTo("4")==0){
                txta_comentario.setText(fe.comentario2_4);
            }
        }
        if(fe.state==3){
            if(name.compareTo("1")==0){
                txta_comentario.setText(fe.comentario3_1);
            }
            if(name.compareTo("2")==0){
                txta_comentario.setText(fe.comentario3_2);
            }
            if(name.compareTo("3")==0){
                txta_comentario.setText(fe.comentario3_3);
            }
            if(name.compareTo("4")==0){
                txta_comentario.setText(fe.comentario3_4);
            }
        }
        if(fe.state==4){
            if(name.compareTo("1")==0){
                txta_comentario.setText(fe.comentario4_1);
            }
            if(name.compareTo("2")==0){
                txta_comentario.setText(fe.comentario4_2);
            }
            if(name.compareTo("3")==0){
                txta_comentario.setText(fe.comentario4_3);
            }
            if(name.compareTo("4")==0){
                txta_comentario.setText(fe.comentario4_4);
            }
        }
    }
    
    public CapturaComentario(FuncionesEvaluacion fe,String name){
        this.fe=fe;
        this.name=name;
        initComponents();
        cargarComentario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_comentario = new javax.swing.JTextArea();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comentarios");
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1, 30, 50));

        txta_comentario.setColumns(20);
        txta_comentario.setLineWrap(true);
        txta_comentario.setRows(5);
        txta_comentario.setTabSize(10);
        txta_comentario.setText("Sin Comentarios");
        txta_comentario.setToolTipText("");
        txta_comentario.setWrapStyleWord(true);
        txta_comentario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escribe tus comentarios", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        txta_comentario.setMinimumSize(new java.awt.Dimension(200, 80));
        jScrollPane1.setViewportView(txta_comentario);

        jPanel1.add(jScrollPane1);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Guardar)
                        .addGap(18, 18, 18)
                        .addComponent(Cancelar)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        if(fe.state==1){
            if(name.compareTo("1")==0){
                fe.comentario1_1=txta_comentario.getText();
            }
            if(name.compareTo("2")==0){
                fe.comentario1_2=txta_comentario.getText();
            }
            if(name.compareTo("3")==0){
                fe.comentario1_3=txta_comentario.getText();
            }
            if(name.compareTo("4")==0){
                fe.comentario1_4=txta_comentario.getText();
            }
            if(name.compareTo("5")==0){
                fe.comentario1_5=txta_comentario.getText();
            }
        }
        if(fe.state==2){
            if(name.compareTo("1")==0){
                fe.comentario2_1=txta_comentario.getText();
            }
            if(name.compareTo("2")==0){
                fe.comentario2_2=txta_comentario.getText();
            }
            if(name.compareTo("3")==0){
                fe.comentario2_3=txta_comentario.getText();
            }
            if(name.compareTo("4")==0){
                fe.comentario2_4=txta_comentario.getText();
            }
        }
        if(fe.state==3){
            if(name.compareTo("1")==0){
                fe.comentario3_1=txta_comentario.getText();
            }
            if(name.compareTo("2")==0){
                fe.comentario3_2=txta_comentario.getText();
            }
            if(name.compareTo("3")==0){
                fe.comentario3_3=txta_comentario.getText();
            }
            if(name.compareTo("4")==0){
                fe.comentario3_4=txta_comentario.getText();
            }
        }
        if(fe.state==4){
            if(name.compareTo("1")==0){
                fe.comentario4_1=txta_comentario.getText();
            }
            if(name.compareTo("2")==0){
                fe.comentario4_2=txta_comentario.getText();
            }
            if(name.compareTo("3")==0){
                fe.comentario4_3=txta_comentario.getText();
            }
            if(name.compareTo("4")==0){
                fe.comentario4_4=txta_comentario.getText();
            }
        }
        this.dispose();
    }//GEN-LAST:event_GuardarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txta_comentario;
    // End of variables declaration//GEN-END:variables
}
